[Variables]

;@Default | Name Visualizer Settings | Icon [\xF61F]

;?Integer | Name BarCount | Description Number of Bars
Bands=40

;?Integer | Name Bar Gap | Description Gap between consecutive Bars
Radius=100

;?Integer | Name Start Angle | Description 
StartAngle=0

;?Integer | Name Total Angle | Description 
TotalAngle=360

;?Integer | Name Height | Description Height of Bars
Height=100

;?Integer | Name Bar Width | Description Width of individual Bars
BarWidth=3

;?Toggle | Name Flip
flipBool=0

;?Integer | Name Minimum Height | Description Minimun height of Bars
MinimumHeight=10

WindowFunction=Kaiser

;?Integer | Name Maximum Sensititvity
MaxSensitivity=45

;?Integer | Name Minimum Sensitivity
MinSensitivity=9

;?Integer | Name Rising Delay | Description in milliseconds
Attack=0

;?Integer | Name Falling Delay | Description in milliseconds
Decay=0

;?Integer | Name Smoothing Level | Description How smooth your visuallizer is
BlurRadius=1

Channel=Auto

AnalyzerPort=DefaultOutput