[Variables]

;@ | Name Vector

;?Integer | Name LayerCount
LayerCount=4

;?Integer | Name Points
VectorBands=12

;?Integer | Name Height
VectorHeight=150

;?Integer | Name Width
VectorWidth=#SCREENAREAWIDTH#

;Integer | Na
Layer1Height=120

Layer2Height=110

Layer3Height=90

Layer4Height=60

Layer1Color=0, 52, 88, 90

Layer2Color=0, 76, 127, 130

Layer3Color=0, 122, 204, 170

Layer4Color=33, 33, 33, 255

;?Integer | Name Angle
Angle=0

WindowFunction=Kaiser

;?Integer | Name Maximum Sensititvity
MaxSensitivity=45

;?Integer | Name Minimum Sensitivity
MinSensitivity=9

;?Integer | Name Rising Delay | Description in milliseconds
Attack=0

;?Integer | Name Falling Delay | Description in milliseconds
Decay=0

;?Integer | Name Smoothing Level | Description How smooth your visuallizer is
BlurRadius=1

Channel=Auto

AnalyzerPort=DefaultOutput