[Variables]

;@ | Name Vector

;?Integer | Name LayerCount
LayerCount=3

;?Integer | Name Points
VectorBands=12

;?Integer | Name Height
VectorHeight=150

;?Integer | Name Width
VectorWidth=#SCREENAREAWIDTH#

;Integer | Na
Layer1Height=110

Layer2Height=90

Layer3Height=60

Layer4Height=220

Layer1Color=128,0,128, 90

Layer2Color=128,0,128, 130

Layer3Color=128,0,128, 250

;?Integer | Name Angle
Angle=0

WindowFunction=Kaiser

;?Integer | Name Maximum Sensititvity
MaxSensitivity=45

;?Integer | Name Minimum Sensitivity
MinSensitivity=9

;?Integer | Name Rising Delay | Description in milliseconds
Attack=0

;?Integer | Name Falling Delay | Description in milliseconds
Decay=0

;?Integer | Name Smoothing Level | Description How smooth your visuallizer is
BlurRadius=1

Channel=Auto

AnalyzerPort=DefaultOutput