[Variables]

;@About | Name Internal settings | Description Changing internal variables requires generating to apply changes. | Icon [\xF259]
;?Integer | Name Scroll speed | Description 
s_ScrollSpeed=30
;? | Name Theme 1 name
s_Theme0Name=Light
;? | Name Theme 2 name
s_Theme1Name=Dark
;? | Name Theme 3 name
s_Theme2Name=Slim

;@Topic | Name Internal | Icon  | 
;? | Name hidden | Hidden 1
s_ScrollTreshold=[#s_PanelH]
s_ScrollRightPanel=0
s_ScrollLeftPanel=0
s_CurrentCategory=0
s_SettingsTheme=2

;@ | Name Generator | Icon [\xE9F5]
;? | 
s_GeneratorRightPanelWidth=350
;? | 
s_GeneratorLeftPanelWidth=50
;? | 
s_GeneratorPanelHeight=300

;@ | Name Debug colors | Icon [\xE783]
;?Toggle | 
s_DebugColors=0
;?Color | 
s_DebugCategoryTitleColor1=255,0,195,100
s_DebugCategoryTitleColor0=0,0,0,0
;?Color | 
s_DebugValueColor1=170,0,255,100
s_DebugValueColor0=0,0,0,0
;?Color | 
s_DebugDescriptionColor1=0,238,255,100
s_DebugDescriptionColor0=0,0,0,0
;?Color | 
s_DebugListColor1=0,255,51,100
s_DebugListColor0=0,0,0,0
;?Color | 
s_DebugListIconColor1=255,255,0,100
s_DebugListIconColor0=0,0,0,0
;?Color | 
s_DebugSeparatorColor1=51,46,46,100
s_DebugSeparatorColor0=0,0,0,0
;?Color | 
s_DebugVariableTitleColor1=255,0,0,100
s_DebugVariableTitleColor0=0,0,0,0
;?Color | 
s_DebugCategoryIconColor1=229,255,0,100
s_DebugCategoryIconColor0=0,0,0,0
;?Color | 
s_DebugToggleColor1=255,0,0,100
s_DebugToggleColor0=0,0,0,0
;?Color | 
s_DebugColorColor1=255,0,0,100
s_DebugColorColor0=0,0,0,0

