
[MeasureL11]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=Layer1Output

[MeasureL12]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=Layer1Output

[MeasureL13]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=Layer1Output

[MeasureL14]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=Layer1Output

[MeasureL15]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=Layer1Output

[MeasureL16]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=Layer1Output

[MeasureL17]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=Layer1Output

[MeasureL18]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=Layer1Output

[MeasureL19]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=Layer1Output

[MeasureL21]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=Layer2Output

[MeasureL22]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=Layer2Output

[MeasureL23]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=Layer2Output

[MeasureL24]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=Layer2Output

[MeasureL25]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=Layer2Output

[MeasureL26]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=Layer2Output

[MeasureL27]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=Layer2Output

[MeasureL28]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=Layer2Output

[MeasureL29]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=Layer2Output

[MeasureL210]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=Layer2Output

[MeasureL211]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=Layer2Output

[MeasureL212]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=Layer2Output

[MeasureL213]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=Layer2Output

[MeasureL214]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=Layer2Output

[MeasureL215]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=Layer2Output

[MeasureL216]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=Layer2Output

[MeasureL217]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=Layer2Output

[MeasureL31]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=Layer3Output

[MeasureL32]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=Layer3Output

[MeasureL33]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=Layer3Output

[MeasureL34]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=Layer3Output

[MeasureL35]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=Layer3Output

[MeasureL36]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=Layer3Output

[MeasureL37]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=Layer3Output

[MeasureL38]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=Layer3Output

[MeasureL39]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=Layer3Output

[MeasureL310]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=Layer3Output

[MeasureL311]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=Layer3Output

[MeasureL312]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=Layer3Output

[MeasureL313]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=Layer3Output

[MeasureL314]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=Layer3Output

[MeasureL315]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=Layer3Output

[MeasureL316]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=Layer3Output

[MeasureL317]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=Layer3Output

[MeasureL318]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=18
Channel=Auto
HandlerName=Layer3Output

[MeasureL319]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=19
Channel=Auto
HandlerName=Layer3Output

[MeasureL320]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=20
Channel=Auto
HandlerName=Layer3Output

[MeasureL321]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=21
Channel=Auto
HandlerName=Layer3Output

[MeasureL322]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=22
Channel=Auto
HandlerName=Layer3Output

[MeasureL323]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=23
Channel=Auto
HandlerName=Layer3Output

[MeasureL324]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=24
Channel=Auto
HandlerName=Layer3Output

[MeasureL325]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=25
Channel=Auto
HandlerName=Layer3Output

[MeasureL326]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=26
Channel=Auto
HandlerName=Layer3Output

[MeasureL327]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=27
Channel=Auto
HandlerName=Layer3Output

[MeasureL328]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=28
Channel=Auto
HandlerName=Layer3Output

[MeasureL329]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=29
Channel=Auto
HandlerName=Layer3Output

[MeasureL330]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=30
Channel=Auto
HandlerName=Layer3Output

[MeasureL331]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=31
Channel=Auto
HandlerName=Layer3Output

[MeasureL332]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=32
Channel=Auto
HandlerName=Layer3Output

[MeasureL333]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=33
Channel=Auto
HandlerName=Layer3Output

[MeasureL41]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=Layer4Output

[MeasureL42]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=Layer4Output

[MeasureL43]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=Layer4Output

[MeasureL44]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=Layer4Output

[MeasureL45]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=Layer4Output

[MeasureL46]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=Layer4Output

[MeasureL47]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=Layer4Output

[MeasureL48]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=Layer4Output

[MeasureL49]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=Layer4Output

[MeasureL410]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=Layer4Output

[MeasureL411]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=Layer4Output

[MeasureL412]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=Layer4Output

[MeasureL413]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=Layer4Output

[MeasureL414]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=Layer4Output

[MeasureL415]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=Layer4Output

[MeasureL416]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=Layer4Output

[MeasureL417]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=Layer4Output

[MeasureL418]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=18
Channel=Auto
HandlerName=Layer4Output

[MeasureL419]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=19
Channel=Auto
HandlerName=Layer4Output

[MeasureL420]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=20
Channel=Auto
HandlerName=Layer4Output

[MeasureL421]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=21
Channel=Auto
HandlerName=Layer4Output

[MeasureL422]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=22
Channel=Auto
HandlerName=Layer4Output

[MeasureL423]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=23
Channel=Auto
HandlerName=Layer4Output

[MeasureL424]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=24
Channel=Auto
HandlerName=Layer4Output

[MeasureL425]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=25
Channel=Auto
HandlerName=Layer4Output

[MeasureL426]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=26
Channel=Auto
HandlerName=Layer4Output

[MeasureL427]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=27
Channel=Auto
HandlerName=Layer4Output

[MeasureL428]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=28
Channel=Auto
HandlerName=Layer4Output

[MeasureL429]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=29
Channel=Auto
HandlerName=Layer4Output

[MeasureL430]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=30
Channel=Auto
HandlerName=Layer4Output

[MeasureL431]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=31
Channel=Auto
HandlerName=Layer4Output

[MeasureL432]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=32
Channel=Auto
HandlerName=Layer4Output

[MeasureL433]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=33
Channel=Auto
HandlerName=Layer4Output

[MeasureL434]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=34
Channel=Auto
HandlerName=Layer4Output

[MeasureL435]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=35
Channel=Auto
HandlerName=Layer4Output

[MeasureL436]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=36
Channel=Auto
HandlerName=Layer4Output

[MeasureL437]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=37
Channel=Auto
HandlerName=Layer4Output

[MeasureL438]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=38
Channel=Auto
HandlerName=Layer4Output

[MeasureL439]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=39
Channel=Auto
HandlerName=Layer4Output

[MeasureL440]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=40
Channel=Auto
HandlerName=Layer4Output

[MeasureL441]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=41
Channel=Auto
HandlerName=Layer4Output

[MeasureL442]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=42
Channel=Auto
HandlerName=Layer4Output

[MeasureL443]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=43
Channel=Auto
HandlerName=Layer4Output

[MeasureL444]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=44
Channel=Auto
HandlerName=Layer4Output

[MeasureL445]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=45
Channel=Auto
HandlerName=Layer4Output

[MeasureL446]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=46
Channel=Auto
HandlerName=Layer4Output

[MeasureL447]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=47
Channel=Auto
HandlerName=Layer4Output

[MeasureL448]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=48
Channel=Auto
HandlerName=Layer4Output

[MeasureL449]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=49
Channel=Auto
HandlerName=Layer4Output

[MeasureL450]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=50
Channel=Auto
HandlerName=Layer4Output

[MeasureL451]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=51
Channel=Auto
HandlerName=Layer4Output

[MeasureL452]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=52
Channel=Auto
HandlerName=Layer4Output

[MeasureL453]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=53
Channel=Auto
HandlerName=Layer4Output

[MeasureL454]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=54
Channel=Auto
HandlerName=Layer4Output

[MeasureL455]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=55
Channel=Auto
HandlerName=Layer4Output

[MeasureL456]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=56
Channel=Auto
HandlerName=Layer4Output

[MeasureL457]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=57
Channel=Auto
HandlerName=Layer4Output

[MeasureL458]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=58
Channel=Auto
HandlerName=Layer4Output

[MeasureL459]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=59
Channel=Auto
HandlerName=Layer4Output

[MeasureL460]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=60
Channel=Auto
HandlerName=Layer4Output

[MeasureL461]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=61
Channel=Auto
HandlerName=Layer4Output

[MeasureL462]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=62
Channel=Auto
HandlerName=Layer4Output

[MeasureL463]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=63
Channel=Auto
HandlerName=Layer4Output

[MeasureL464]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=64
Channel=Auto
HandlerName=Layer4Output

[MeasureL465]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=65
Channel=Auto
HandlerName=Layer4Output

