
[MeasureL11]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=Layer1Output

[MeasureL12]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=Layer1Output

[MeasureL13]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=Layer1Output

[MeasureL14]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=Layer1Output

[MeasureL15]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=Layer1Output

[MeasureL16]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=Layer1Output

[MeasureL17]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=Layer1Output

[MeasureL18]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=Layer1Output

[MeasureL19]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=Layer1Output

[MeasureL110]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=Layer1Output

[MeasureL111]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=Layer1Output

[MeasureL112]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=Layer1Output

[MeasureL21]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=Layer2Output

[MeasureL22]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=Layer2Output

[MeasureL23]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=Layer2Output

[MeasureL24]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=Layer2Output

[MeasureL25]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=Layer2Output

[MeasureL26]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=Layer2Output

[MeasureL27]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=Layer2Output

[MeasureL28]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=Layer2Output

[MeasureL29]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=Layer2Output

[MeasureL210]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=Layer2Output

[MeasureL211]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=Layer2Output

[MeasureL212]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=Layer2Output

[MeasureL213]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=Layer2Output

[MeasureL214]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=Layer2Output

[MeasureL215]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=Layer2Output

[MeasureL216]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=Layer2Output

[MeasureL217]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=Layer2Output

[MeasureL218]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=18
Channel=Auto
HandlerName=Layer2Output

[MeasureL219]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=19
Channel=Auto
HandlerName=Layer2Output

[MeasureL220]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=20
Channel=Auto
HandlerName=Layer2Output

[MeasureL221]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=21
Channel=Auto
HandlerName=Layer2Output

[MeasureL222]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=22
Channel=Auto
HandlerName=Layer2Output

[MeasureL223]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=23
Channel=Auto
HandlerName=Layer2Output

[MeasureL31]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=1
Channel=Auto
HandlerName=Layer3Output

[MeasureL32]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=2
Channel=Auto
HandlerName=Layer3Output

[MeasureL33]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=3
Channel=Auto
HandlerName=Layer3Output

[MeasureL34]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=4
Channel=Auto
HandlerName=Layer3Output

[MeasureL35]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=5
Channel=Auto
HandlerName=Layer3Output

[MeasureL36]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=6
Channel=Auto
HandlerName=Layer3Output

[MeasureL37]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=7
Channel=Auto
HandlerName=Layer3Output

[MeasureL38]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=8
Channel=Auto
HandlerName=Layer3Output

[MeasureL39]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=9
Channel=Auto
HandlerName=Layer3Output

[MeasureL310]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=10
Channel=Auto
HandlerName=Layer3Output

[MeasureL311]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=11
Channel=Auto
HandlerName=Layer3Output

[MeasureL312]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=12
Channel=Auto
HandlerName=Layer3Output

[MeasureL313]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=13
Channel=Auto
HandlerName=Layer3Output

[MeasureL314]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=14
Channel=Auto
HandlerName=Layer3Output

[MeasureL315]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=15
Channel=Auto
HandlerName=Layer3Output

[MeasureL316]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=16
Channel=Auto
HandlerName=Layer3Output

[MeasureL317]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=17
Channel=Auto
HandlerName=Layer3Output

[MeasureL318]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=18
Channel=Auto
HandlerName=Layer3Output

[MeasureL319]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=19
Channel=Auto
HandlerName=Layer3Output

[MeasureL320]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=20
Channel=Auto
HandlerName=Layer3Output

[MeasureL321]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=21
Channel=Auto
HandlerName=Layer3Output

[MeasureL322]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=22
Channel=Auto
HandlerName=Layer3Output

[MeasureL323]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=23
Channel=Auto
HandlerName=Layer3Output

[MeasureL324]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=24
Channel=Auto
HandlerName=Layer3Output

[MeasureL325]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=25
Channel=Auto
HandlerName=Layer3Output

[MeasureL326]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=26
Channel=Auto
HandlerName=Layer3Output

[MeasureL327]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=27
Channel=Auto
HandlerName=Layer3Output

[MeasureL328]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=28
Channel=Auto
HandlerName=Layer3Output

[MeasureL329]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=29
Channel=Auto
HandlerName=Layer3Output

[MeasureL330]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=30
Channel=Auto
HandlerName=Layer3Output

[MeasureL331]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=31
Channel=Auto
HandlerName=Layer3Output

[MeasureL332]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=32
Channel=Auto
HandlerName=Layer3Output

[MeasureL333]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=33
Channel=Auto
HandlerName=Layer3Output

[MeasureL334]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=34
Channel=Auto
HandlerName=Layer3Output

[MeasureL335]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=35
Channel=Auto
HandlerName=Layer3Output

[MeasureL336]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=36
Channel=Auto
HandlerName=Layer3Output

[MeasureL337]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=37
Channel=Auto
HandlerName=Layer3Output

[MeasureL338]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=38
Channel=Auto
HandlerName=Layer3Output

[MeasureL339]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=39
Channel=Auto
HandlerName=Layer3Output

[MeasureL340]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=40
Channel=Auto
HandlerName=Layer3Output

[MeasureL341]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=41
Channel=Auto
HandlerName=Layer3Output

[MeasureL342]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=42
Channel=Auto
HandlerName=Layer3Output

[MeasureL343]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=43
Channel=Auto
HandlerName=Layer3Output

[MeasureL344]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=44
Channel=Auto
HandlerName=Layer3Output

[MeasureL345]
Measure=Plugin
Plugin=AudioAnalyzer
Parent=AudioAnalyzer
Type=Child
Index=45
Channel=Auto
HandlerName=Layer3Output

