[Variables]
;@ | Name MirrorX

;?Integer | Name First X-Offset
Group1XOffset=0

;?Integer | Name First Y-Offset
Group1YOffset=0

Group1XFlip=0

Group1YFlip=0

;?Integer | Name Second X-Offset
Group2XOffset=0

;?Integer | Name Second Y-Offset
Group2YOffset=0

Group2XFlip=0

Group2YFlip=0

;?Integer | Name Third X-Offset
Group3XOffset=0

;?Integer | Name Third Y-Offset
Group3YOffset=0

Group3XFlip=0

Group3YFlip=0

;?Integer | Name Fourth X-Offset
Group4XOffset=0

;?Integer | Name Fourth Y-Offset
Group4YOffset=0

Group4XFlip=0

Group4YFlip=0
