;Category list styles
[ListIcon]
FontFace=#s_IconFontFace#
AccurateText=1
AntiAlias=1
Y=0R
X=0
SolidColor=[#s_DebugListIconColor[#s_DebugColors]] 
FontColor=[#s_FontColor]

[ListDefaultIcon]
Padding=[#s_ListDefaultLeftPadding],[#s_ListYPadding],0,[#s_ListYPadding]
FontSize=#s_FontSize2#
FontColor=[#s_FontColor]

[ListTopicIcon]
Padding=[#s_ListTopicLeftPadding],[#s_ListYPadding],0,[#s_ListYPadding]
FontSize=#s_FontSize3#
FontColor=[#s_FontColor]

[ListAboutIcon]
Padding=[#s_ListAboutLeftPadding],([#s_ListYPadding] + 3),0,[#s_ListYPadding]
FontSize=#s_FontSize1#
FontColor=[#s_FontColor]

[ListItem]
Padding=0,[#s_ListYPadding],0,[#s_ListYPadding]
SolidColor=[#s_DebugListColor[#s_DebugColors]] 
FontFace=#s_FontFace#
ClipString=2
FontColor=[#s_FontColor]
DynamicVariables=1
AccurateText=1
AntiAlias=1
X=0R
Y=0r

[ListDefaultItem]
FontSize=#s_FontSize3#
FontColor=[#s_FontColor]
;solidColor=0,0,255,100

[ListTopicItem]
FontSize=#s_FontSize4#
FontColor=[#s_FontColor]
;solidColor=0,255,0,100

[ListAboutItem]
FontSize=#s_FontSize2#
FontColor=[#s_FontColor]
;solidColor=255,0,0,100

