
[Shape]
Meter=Shape
DynamicVariables=1
W=799
H=304
TransformationMatrix=1;0;0;1;0;0

Shape=Rectangle 1, 150, 5, (-1*Clamp(150*[Measure1], 1, 150)), 2 | Fill Color [#Color1]

Shape2=Rectangle 9, 150, 5, (-1*Clamp(150*[Measure2], 1, 150)), 2 | Fill Color [#Color2]

Shape3=Rectangle 17, 150, 5, (-1*Clamp(150*[Measure3], 1, 150)), 2 | Fill Color [#Color3]

Shape4=Rectangle 25, 150, 5, (-1*Clamp(150*[Measure4], 1, 150)), 2 | Fill Color [#Color4]

Shape5=Rectangle 33, 150, 5, (-1*Clamp(150*[Measure5], 1, 150)), 2 | Fill Color [#Color5]

Shape6=Rectangle 41, 150, 5, (-1*Clamp(150*[Measure6], 1, 150)), 2 | Fill Color [#Color6]

Shape7=Rectangle 49, 150, 5, (-1*Clamp(150*[Measure7], 1, 150)), 2 | Fill Color [#Color7]

Shape8=Rectangle 57, 150, 5, (-1*Clamp(150*[Measure8], 1, 150)), 2 | Fill Color [#Color8]

Shape9=Rectangle 65, 150, 5, (-1*Clamp(150*[Measure9], 1, 150)), 2 | Fill Color [#Color9]

Shape10=Rectangle 73, 150, 5, (-1*Clamp(150*[Measure10], 1, 150)), 2 | Fill Color [#Color10]

Shape11=Rectangle 81, 150, 5, (-1*Clamp(150*[Measure11], 1, 150)), 2 | Fill Color [#Color11]

Shape12=Rectangle 89, 150, 5, (-1*Clamp(150*[Measure12], 1, 150)), 2 | Fill Color [#Color12]

Shape13=Rectangle 97, 150, 5, (-1*Clamp(150*[Measure13], 1, 150)), 2 | Fill Color [#Color13]

Shape14=Rectangle 105, 150, 5, (-1*Clamp(150*[Measure14], 1, 150)), 2 | Fill Color [#Color14]

Shape15=Rectangle 113, 150, 5, (-1*Clamp(150*[Measure15], 1, 150)), 2 | Fill Color [#Color15]

Shape16=Rectangle 121, 150, 5, (-1*Clamp(150*[Measure16], 1, 150)), 2 | Fill Color [#Color16]

Shape17=Rectangle 129, 150, 5, (-1*Clamp(150*[Measure17], 1, 150)), 2 | Fill Color [#Color17]

Shape18=Rectangle 137, 150, 5, (-1*Clamp(150*[Measure18], 1, 150)), 2 | Fill Color [#Color18]

Shape19=Rectangle 145, 150, 5, (-1*Clamp(150*[Measure19], 1, 150)), 2 | Fill Color [#Color19]

Shape20=Rectangle 153, 150, 5, (-1*Clamp(150*[Measure20], 1, 150)), 2 | Fill Color [#Color20]

Shape21=Rectangle 161, 150, 5, (-1*Clamp(150*[Measure21], 1, 150)), 2 | Fill Color [#Color21]

Shape22=Rectangle 169, 150, 5, (-1*Clamp(150*[Measure22], 1, 150)), 2 | Fill Color [#Color22]

Shape23=Rectangle 177, 150, 5, (-1*Clamp(150*[Measure23], 1, 150)), 2 | Fill Color [#Color23]

Shape24=Rectangle 185, 150, 5, (-1*Clamp(150*[Measure24], 1, 150)), 2 | Fill Color [#Color24]

Shape25=Rectangle 193, 150, 5, (-1*Clamp(150*[Measure25], 1, 150)), 2 | Fill Color [#Color25]

Shape26=Rectangle 201, 150, 5, (-1*Clamp(150*[Measure26], 1, 150)), 2 | Fill Color [#Color26]

Shape27=Rectangle 209, 150, 5, (-1*Clamp(150*[Measure27], 1, 150)), 2 | Fill Color [#Color27]

Shape28=Rectangle 217, 150, 5, (-1*Clamp(150*[Measure28], 1, 150)), 2 | Fill Color [#Color28]

Shape29=Rectangle 225, 150, 5, (-1*Clamp(150*[Measure29], 1, 150)), 2 | Fill Color [#Color29]

Shape30=Rectangle 233, 150, 5, (-1*Clamp(150*[Measure30], 1, 150)), 2 | Fill Color [#Color30]

Shape31=Rectangle 241, 150, 5, (-1*Clamp(150*[Measure31], 1, 150)), 2 | Fill Color [#Color31]

Shape32=Rectangle 249, 150, 5, (-1*Clamp(150*[Measure32], 1, 150)), 2 | Fill Color [#Color32]

Shape33=Rectangle 257, 150, 5, (-1*Clamp(150*[Measure33], 1, 150)), 2 | Fill Color [#Color33]

Shape34=Rectangle 265, 150, 5, (-1*Clamp(150*[Measure34], 1, 150)), 2 | Fill Color [#Color34]

Shape35=Rectangle 273, 150, 5, (-1*Clamp(150*[Measure35], 1, 150)), 2 | Fill Color [#Color35]

Shape36=Rectangle 281, 150, 5, (-1*Clamp(150*[Measure36], 1, 150)), 2 | Fill Color [#Color36]

Shape37=Rectangle 289, 150, 5, (-1*Clamp(150*[Measure37], 1, 150)), 2 | Fill Color [#Color37]

Shape38=Rectangle 297, 150, 5, (-1*Clamp(150*[Measure38], 1, 150)), 2 | Fill Color [#Color38]

Shape39=Rectangle 305, 150, 5, (-1*Clamp(150*[Measure39], 1, 150)), 2 | Fill Color [#Color39]

Shape40=Rectangle 313, 150, 5, (-1*Clamp(150*[Measure40], 1, 150)), 2 | Fill Color [#Color40]

Shape41=Rectangle 321, 150, 5, (-1*Clamp(150*[Measure41], 1, 150)), 2 | Fill Color [#Color41]

Shape42=Rectangle 329, 150, 5, (-1*Clamp(150*[Measure42], 1, 150)), 2 | Fill Color [#Color42]

Shape43=Rectangle 337, 150, 5, (-1*Clamp(150*[Measure43], 1, 150)), 2 | Fill Color [#Color43]

Shape44=Rectangle 345, 150, 5, (-1*Clamp(150*[Measure44], 1, 150)), 2 | Fill Color [#Color44]

Shape45=Rectangle 353, 150, 5, (-1*Clamp(150*[Measure45], 1, 150)), 2 | Fill Color [#Color45]

Shape46=Rectangle 361, 150, 5, (-1*Clamp(150*[Measure46], 1, 150)), 2 | Fill Color [#Color46]

Shape47=Rectangle 369, 150, 5, (-1*Clamp(150*[Measure47], 1, 150)), 2 | Fill Color [#Color47]

Shape48=Rectangle 377, 150, 5, (-1*Clamp(150*[Measure48], 1, 150)), 2 | Fill Color [#Color48]

Shape49=Rectangle 385, 150, 5, (-1*Clamp(150*[Measure49], 1, 150)), 2 | Fill Color [#Color49]

Shape50=Rectangle 393, 150, 5, (-1*Clamp(150*[Measure50], 1, 150)), 2 | Fill Color [#Color50]

Shape51=Rectangle 401, 150, 5, (-1*Clamp(150*([Measure50]), 1, 150)), 2 | Fill Color [#Color50]

Shape52=Rectangle 409, 150, 5, (-1*Clamp(150*([Measure49]), 1, 150)), 2 | Fill Color [#Color49]

Shape53=Rectangle 417, 150, 5, (-1*Clamp(150*([Measure48]), 1, 150)), 2 | Fill Color [#Color48]

Shape54=Rectangle 425, 150, 5, (-1*Clamp(150*([Measure47]), 1, 150)), 2 | Fill Color [#Color47]

Shape55=Rectangle 433, 150, 5, (-1*Clamp(150*([Measure46]), 1, 150)), 2 | Fill Color [#Color46]

Shape56=Rectangle 441, 150, 5, (-1*Clamp(150*([Measure45]), 1, 150)), 2 | Fill Color [#Color45]

Shape57=Rectangle 449, 150, 5, (-1*Clamp(150*([Measure44]), 1, 150)), 2 | Fill Color [#Color44]

Shape58=Rectangle 457, 150, 5, (-1*Clamp(150*([Measure43]), 1, 150)), 2 | Fill Color [#Color43]

Shape59=Rectangle 465, 150, 5, (-1*Clamp(150*([Measure42]), 1, 150)), 2 | Fill Color [#Color42]

Shape60=Rectangle 473, 150, 5, (-1*Clamp(150*([Measure41]), 1, 150)), 2 | Fill Color [#Color41]

Shape61=Rectangle 481, 150, 5, (-1*Clamp(150*([Measure40]), 1, 150)), 2 | Fill Color [#Color40]

Shape62=Rectangle 489, 150, 5, (-1*Clamp(150*([Measure39]), 1, 150)), 2 | Fill Color [#Color39]

Shape63=Rectangle 497, 150, 5, (-1*Clamp(150*([Measure38]), 1, 150)), 2 | Fill Color [#Color38]

Shape64=Rectangle 505, 150, 5, (-1*Clamp(150*([Measure37]), 1, 150)), 2 | Fill Color [#Color37]

Shape65=Rectangle 513, 150, 5, (-1*Clamp(150*([Measure36]), 1, 150)), 2 | Fill Color [#Color36]

Shape66=Rectangle 521, 150, 5, (-1*Clamp(150*([Measure35]), 1, 150)), 2 | Fill Color [#Color35]

Shape67=Rectangle 529, 150, 5, (-1*Clamp(150*([Measure34]), 1, 150)), 2 | Fill Color [#Color34]

Shape68=Rectangle 537, 150, 5, (-1*Clamp(150*([Measure33]), 1, 150)), 2 | Fill Color [#Color33]

Shape69=Rectangle 545, 150, 5, (-1*Clamp(150*([Measure32]), 1, 150)), 2 | Fill Color [#Color32]

Shape70=Rectangle 553, 150, 5, (-1*Clamp(150*([Measure31]), 1, 150)), 2 | Fill Color [#Color31]

Shape71=Rectangle 561, 150, 5, (-1*Clamp(150*([Measure30]), 1, 150)), 2 | Fill Color [#Color30]

Shape72=Rectangle 569, 150, 5, (-1*Clamp(150*([Measure29]), 1, 150)), 2 | Fill Color [#Color29]

Shape73=Rectangle 577, 150, 5, (-1*Clamp(150*([Measure28]), 1, 150)), 2 | Fill Color [#Color28]

Shape74=Rectangle 585, 150, 5, (-1*Clamp(150*([Measure27]), 1, 150)), 2 | Fill Color [#Color27]

Shape75=Rectangle 593, 150, 5, (-1*Clamp(150*([Measure26]), 1, 150)), 2 | Fill Color [#Color26]

Shape76=Rectangle 601, 150, 5, (-1*Clamp(150*([Measure25]), 1, 150)), 2 | Fill Color [#Color25]

Shape77=Rectangle 609, 150, 5, (-1*Clamp(150*([Measure24]), 1, 150)), 2 | Fill Color [#Color24]

Shape78=Rectangle 617, 150, 5, (-1*Clamp(150*([Measure23]), 1, 150)), 2 | Fill Color [#Color23]

Shape79=Rectangle 625, 150, 5, (-1*Clamp(150*([Measure22]), 1, 150)), 2 | Fill Color [#Color22]

Shape80=Rectangle 633, 150, 5, (-1*Clamp(150*([Measure21]), 1, 150)), 2 | Fill Color [#Color21]

Shape81=Rectangle 641, 150, 5, (-1*Clamp(150*([Measure20]), 1, 150)), 2 | Fill Color [#Color20]

Shape82=Rectangle 649, 150, 5, (-1*Clamp(150*([Measure19]), 1, 150)), 2 | Fill Color [#Color19]

Shape83=Rectangle 657, 150, 5, (-1*Clamp(150*([Measure18]), 1, 150)), 2 | Fill Color [#Color18]

Shape84=Rectangle 665, 150, 5, (-1*Clamp(150*([Measure17]), 1, 150)), 2 | Fill Color [#Color17]

Shape85=Rectangle 673, 150, 5, (-1*Clamp(150*([Measure16]), 1, 150)), 2 | Fill Color [#Color16]

Shape86=Rectangle 681, 150, 5, (-1*Clamp(150*([Measure15]), 1, 150)), 2 | Fill Color [#Color15]

Shape87=Rectangle 689, 150, 5, (-1*Clamp(150*([Measure14]), 1, 150)), 2 | Fill Color [#Color14]

Shape88=Rectangle 697, 150, 5, (-1*Clamp(150*([Measure13]), 1, 150)), 2 | Fill Color [#Color13]

Shape89=Rectangle 705, 150, 5, (-1*Clamp(150*([Measure12]), 1, 150)), 2 | Fill Color [#Color12]

Shape90=Rectangle 713, 150, 5, (-1*Clamp(150*([Measure11]), 1, 150)), 2 | Fill Color [#Color11]

Shape91=Rectangle 721, 150, 5, (-1*Clamp(150*([Measure10]), 1, 150)), 2 | Fill Color [#Color10]

Shape92=Rectangle 729, 150, 5, (-1*Clamp(150*([Measure9]), 1, 150)), 2 | Fill Color [#Color9]

Shape93=Rectangle 737, 150, 5, (-1*Clamp(150*([Measure8]), 1, 150)), 2 | Fill Color [#Color8]

Shape94=Rectangle 745, 150, 5, (-1*Clamp(150*([Measure7]), 1, 150)), 2 | Fill Color [#Color7]

Shape95=Rectangle 753, 150, 5, (-1*Clamp(150*([Measure6]), 1, 150)), 2 | Fill Color [#Color6]

Shape96=Rectangle 761, 150, 5, (-1*Clamp(150*([Measure5]), 1, 150)), 2 | Fill Color [#Color5]

Shape97=Rectangle 769, 150, 5, (-1*Clamp(150*([Measure4]), 1, 150)), 2 | Fill Color [#Color4]

Shape98=Rectangle 777, 150, 5, (-1*Clamp(150*([Measure3]), 1, 150)), 2 | Fill Color [#Color3]

Shape99=Rectangle 785, 150, 5, (-1*Clamp(150*([Measure2]), 1, 150)), 2 | Fill Color [#Color2]

Shape100=Rectangle 793, 150, 5, (-1*Clamp(150*([Measure1]), 1, 150)), 2 | Fill Color [#Color1]

Shape101=Rectangle 1, 152, 5, (1*Clamp(150*[Measure1], 1, 150)), 2 | Fill Color [#Color1]

Shape102=Rectangle 9, 152, 5, (1*Clamp(150*[Measure2], 1, 150)), 2 | Fill Color [#Color2]

Shape103=Rectangle 17, 152, 5, (1*Clamp(150*[Measure3], 1, 150)), 2 | Fill Color [#Color3]

Shape104=Rectangle 25, 152, 5, (1*Clamp(150*[Measure4], 1, 150)), 2 | Fill Color [#Color4]

Shape105=Rectangle 33, 152, 5, (1*Clamp(150*[Measure5], 1, 150)), 2 | Fill Color [#Color5]

Shape106=Rectangle 41, 152, 5, (1*Clamp(150*[Measure6], 1, 150)), 2 | Fill Color [#Color6]

Shape107=Rectangle 49, 152, 5, (1*Clamp(150*[Measure7], 1, 150)), 2 | Fill Color [#Color7]

Shape108=Rectangle 57, 152, 5, (1*Clamp(150*[Measure8], 1, 150)), 2 | Fill Color [#Color8]

Shape109=Rectangle 65, 152, 5, (1*Clamp(150*[Measure9], 1, 150)), 2 | Fill Color [#Color9]

Shape110=Rectangle 73, 152, 5, (1*Clamp(150*[Measure10], 1, 150)), 2 | Fill Color [#Color10]

Shape111=Rectangle 81, 152, 5, (1*Clamp(150*[Measure11], 1, 150)), 2 | Fill Color [#Color11]

Shape112=Rectangle 89, 152, 5, (1*Clamp(150*[Measure12], 1, 150)), 2 | Fill Color [#Color12]

Shape113=Rectangle 97, 152, 5, (1*Clamp(150*[Measure13], 1, 150)), 2 | Fill Color [#Color13]

Shape114=Rectangle 105, 152, 5, (1*Clamp(150*[Measure14], 1, 150)), 2 | Fill Color [#Color14]

Shape115=Rectangle 113, 152, 5, (1*Clamp(150*[Measure15], 1, 150)), 2 | Fill Color [#Color15]

Shape116=Rectangle 121, 152, 5, (1*Clamp(150*[Measure16], 1, 150)), 2 | Fill Color [#Color16]

Shape117=Rectangle 129, 152, 5, (1*Clamp(150*[Measure17], 1, 150)), 2 | Fill Color [#Color17]

Shape118=Rectangle 137, 152, 5, (1*Clamp(150*[Measure18], 1, 150)), 2 | Fill Color [#Color18]

Shape119=Rectangle 145, 152, 5, (1*Clamp(150*[Measure19], 1, 150)), 2 | Fill Color [#Color19]

Shape120=Rectangle 153, 152, 5, (1*Clamp(150*[Measure20], 1, 150)), 2 | Fill Color [#Color20]

Shape121=Rectangle 161, 152, 5, (1*Clamp(150*[Measure21], 1, 150)), 2 | Fill Color [#Color21]

Shape122=Rectangle 169, 152, 5, (1*Clamp(150*[Measure22], 1, 150)), 2 | Fill Color [#Color22]

Shape123=Rectangle 177, 152, 5, (1*Clamp(150*[Measure23], 1, 150)), 2 | Fill Color [#Color23]

Shape124=Rectangle 185, 152, 5, (1*Clamp(150*[Measure24], 1, 150)), 2 | Fill Color [#Color24]

Shape125=Rectangle 193, 152, 5, (1*Clamp(150*[Measure25], 1, 150)), 2 | Fill Color [#Color25]

Shape126=Rectangle 201, 152, 5, (1*Clamp(150*[Measure26], 1, 150)), 2 | Fill Color [#Color26]

Shape127=Rectangle 209, 152, 5, (1*Clamp(150*[Measure27], 1, 150)), 2 | Fill Color [#Color27]

Shape128=Rectangle 217, 152, 5, (1*Clamp(150*[Measure28], 1, 150)), 2 | Fill Color [#Color28]

Shape129=Rectangle 225, 152, 5, (1*Clamp(150*[Measure29], 1, 150)), 2 | Fill Color [#Color29]

Shape130=Rectangle 233, 152, 5, (1*Clamp(150*[Measure30], 1, 150)), 2 | Fill Color [#Color30]

Shape131=Rectangle 241, 152, 5, (1*Clamp(150*[Measure31], 1, 150)), 2 | Fill Color [#Color31]

Shape132=Rectangle 249, 152, 5, (1*Clamp(150*[Measure32], 1, 150)), 2 | Fill Color [#Color32]

Shape133=Rectangle 257, 152, 5, (1*Clamp(150*[Measure33], 1, 150)), 2 | Fill Color [#Color33]

Shape134=Rectangle 265, 152, 5, (1*Clamp(150*[Measure34], 1, 150)), 2 | Fill Color [#Color34]

Shape135=Rectangle 273, 152, 5, (1*Clamp(150*[Measure35], 1, 150)), 2 | Fill Color [#Color35]

Shape136=Rectangle 281, 152, 5, (1*Clamp(150*[Measure36], 1, 150)), 2 | Fill Color [#Color36]

Shape137=Rectangle 289, 152, 5, (1*Clamp(150*[Measure37], 1, 150)), 2 | Fill Color [#Color37]

Shape138=Rectangle 297, 152, 5, (1*Clamp(150*[Measure38], 1, 150)), 2 | Fill Color [#Color38]

Shape139=Rectangle 305, 152, 5, (1*Clamp(150*[Measure39], 1, 150)), 2 | Fill Color [#Color39]

Shape140=Rectangle 313, 152, 5, (1*Clamp(150*[Measure40], 1, 150)), 2 | Fill Color [#Color40]

Shape141=Rectangle 321, 152, 5, (1*Clamp(150*[Measure41], 1, 150)), 2 | Fill Color [#Color41]

Shape142=Rectangle 329, 152, 5, (1*Clamp(150*[Measure42], 1, 150)), 2 | Fill Color [#Color42]

Shape143=Rectangle 337, 152, 5, (1*Clamp(150*[Measure43], 1, 150)), 2 | Fill Color [#Color43]

Shape144=Rectangle 345, 152, 5, (1*Clamp(150*[Measure44], 1, 150)), 2 | Fill Color [#Color44]

Shape145=Rectangle 353, 152, 5, (1*Clamp(150*[Measure45], 1, 150)), 2 | Fill Color [#Color45]

Shape146=Rectangle 361, 152, 5, (1*Clamp(150*[Measure46], 1, 150)), 2 | Fill Color [#Color46]

Shape147=Rectangle 369, 152, 5, (1*Clamp(150*[Measure47], 1, 150)), 2 | Fill Color [#Color47]

Shape148=Rectangle 377, 152, 5, (1*Clamp(150*[Measure48], 1, 150)), 2 | Fill Color [#Color48]

Shape149=Rectangle 385, 152, 5, (1*Clamp(150*[Measure49], 1, 150)), 2 | Fill Color [#Color49]

Shape150=Rectangle 393, 152, 5, (1*Clamp(150*[Measure50], 1, 150)), 2 | Fill Color [#Color50]

Shape151=Rectangle 401, 152, 5, (1*Clamp(150*[Measure50], 1, 150)), 2 | Fill Color [#Color50]

Shape152=Rectangle 409, 152, 5, (1*Clamp(150*[Measure49], 1, 150)), 2 | Fill Color [#Color49]

Shape153=Rectangle 417, 152, 5, (1*Clamp(150*[Measure48], 1, 150)), 2 | Fill Color [#Color48]

Shape154=Rectangle 425, 152, 5, (1*Clamp(150*[Measure47], 1, 150)), 2 | Fill Color [#Color47]

Shape155=Rectangle 433, 152, 5, (1*Clamp(150*[Measure46], 1, 150)), 2 | Fill Color [#Color46]

Shape156=Rectangle 441, 152, 5, (1*Clamp(150*[Measure45], 1, 150)), 2 | Fill Color [#Color45]

Shape157=Rectangle 449, 152, 5, (1*Clamp(150*[Measure44], 1, 150)), 2 | Fill Color [#Color44]

Shape158=Rectangle 457, 152, 5, (1*Clamp(150*[Measure43], 1, 150)), 2 | Fill Color [#Color43]

Shape159=Rectangle 465, 152, 5, (1*Clamp(150*[Measure42], 1, 150)), 2 | Fill Color [#Color42]

Shape160=Rectangle 473, 152, 5, (1*Clamp(150*[Measure41], 1, 150)), 2 | Fill Color [#Color41]

Shape161=Rectangle 481, 152, 5, (1*Clamp(150*[Measure40], 1, 150)), 2 | Fill Color [#Color40]

Shape162=Rectangle 489, 152, 5, (1*Clamp(150*[Measure39], 1, 150)), 2 | Fill Color [#Color39]

Shape163=Rectangle 497, 152, 5, (1*Clamp(150*[Measure38], 1, 150)), 2 | Fill Color [#Color38]

Shape164=Rectangle 505, 152, 5, (1*Clamp(150*[Measure37], 1, 150)), 2 | Fill Color [#Color37]

Shape165=Rectangle 513, 152, 5, (1*Clamp(150*[Measure36], 1, 150)), 2 | Fill Color [#Color36]

Shape166=Rectangle 521, 152, 5, (1*Clamp(150*[Measure35], 1, 150)), 2 | Fill Color [#Color35]

Shape167=Rectangle 529, 152, 5, (1*Clamp(150*[Measure34], 1, 150)), 2 | Fill Color [#Color34]

Shape168=Rectangle 537, 152, 5, (1*Clamp(150*[Measure33], 1, 150)), 2 | Fill Color [#Color33]

Shape169=Rectangle 545, 152, 5, (1*Clamp(150*[Measure32], 1, 150)), 2 | Fill Color [#Color32]

Shape170=Rectangle 553, 152, 5, (1*Clamp(150*[Measure31], 1, 150)), 2 | Fill Color [#Color31]

Shape171=Rectangle 561, 152, 5, (1*Clamp(150*[Measure30], 1, 150)), 2 | Fill Color [#Color30]

Shape172=Rectangle 569, 152, 5, (1*Clamp(150*[Measure29], 1, 150)), 2 | Fill Color [#Color29]

Shape173=Rectangle 577, 152, 5, (1*Clamp(150*[Measure28], 1, 150)), 2 | Fill Color [#Color28]

Shape174=Rectangle 585, 152, 5, (1*Clamp(150*[Measure27], 1, 150)), 2 | Fill Color [#Color27]

Shape175=Rectangle 593, 152, 5, (1*Clamp(150*[Measure26], 1, 150)), 2 | Fill Color [#Color26]

Shape176=Rectangle 601, 152, 5, (1*Clamp(150*[Measure25], 1, 150)), 2 | Fill Color [#Color25]

Shape177=Rectangle 609, 152, 5, (1*Clamp(150*[Measure24], 1, 150)), 2 | Fill Color [#Color24]

Shape178=Rectangle 617, 152, 5, (1*Clamp(150*[Measure23], 1, 150)), 2 | Fill Color [#Color23]

Shape179=Rectangle 625, 152, 5, (1*Clamp(150*[Measure22], 1, 150)), 2 | Fill Color [#Color22]

Shape180=Rectangle 633, 152, 5, (1*Clamp(150*[Measure21], 1, 150)), 2 | Fill Color [#Color21]

Shape181=Rectangle 641, 152, 5, (1*Clamp(150*[Measure20], 1, 150)), 2 | Fill Color [#Color20]

Shape182=Rectangle 649, 152, 5, (1*Clamp(150*[Measure19], 1, 150)), 2 | Fill Color [#Color19]

Shape183=Rectangle 657, 152, 5, (1*Clamp(150*[Measure18], 1, 150)), 2 | Fill Color [#Color18]

Shape184=Rectangle 665, 152, 5, (1*Clamp(150*[Measure17], 1, 150)), 2 | Fill Color [#Color17]

Shape185=Rectangle 673, 152, 5, (1*Clamp(150*[Measure16], 1, 150)), 2 | Fill Color [#Color16]

Shape186=Rectangle 681, 152, 5, (1*Clamp(150*[Measure15], 1, 150)), 2 | Fill Color [#Color15]

Shape187=Rectangle 689, 152, 5, (1*Clamp(150*[Measure14], 1, 150)), 2 | Fill Color [#Color14]

Shape188=Rectangle 697, 152, 5, (1*Clamp(150*[Measure13], 1, 150)), 2 | Fill Color [#Color13]

Shape189=Rectangle 705, 152, 5, (1*Clamp(150*[Measure12], 1, 150)), 2 | Fill Color [#Color12]

Shape190=Rectangle 713, 152, 5, (1*Clamp(150*[Measure11], 1, 150)), 2 | Fill Color [#Color11]

Shape191=Rectangle 721, 152, 5, (1*Clamp(150*[Measure10], 1, 150)), 2 | Fill Color [#Color10]

Shape192=Rectangle 729, 152, 5, (1*Clamp(150*[Measure9], 1, 150)), 2 | Fill Color [#Color9]

Shape193=Rectangle 737, 152, 5, (1*Clamp(150*[Measure8], 1, 150)), 2 | Fill Color [#Color8]

Shape194=Rectangle 745, 152, 5, (1*Clamp(150*[Measure7], 1, 150)), 2 | Fill Color [#Color7]

Shape195=Rectangle 753, 152, 5, (1*Clamp(150*[Measure6], 1, 150)), 2 | Fill Color [#Color6]

Shape196=Rectangle 761, 152, 5, (1*Clamp(150*[Measure5], 1, 150)), 2 | Fill Color [#Color5]

Shape197=Rectangle 769, 152, 5, (1*Clamp(150*[Measure4], 1, 150)), 2 | Fill Color [#Color4]

Shape198=Rectangle 777, 152, 5, (1*Clamp(150*[Measure3], 1, 150)), 2 | Fill Color [#Color3]

Shape199=Rectangle 785, 152, 5, (1*Clamp(150*[Measure2], 1, 150)), 2 | Fill Color [#Color2]

Shape200=Rectangle 793, 152, 5, (1*Clamp(150*[Measure1], 1, 150)), 2 | Fill Color [#Color1]

